### ISSUE TITLE
d3.scaleTime() does not work

### ISSUE THREAD

**Issue by jmiba** [webjars/d3js#32]
In 6.2.0 d3.scaleTime() does not work.

The config looks like this

// webjar config for d3js
requirejs.config({
    paths: { "d3js": webjars.path("d3js", "d3") },
    shim: { "d3js": { "exports": "d3" } }
});

Using

define(['d3js'], function(d3) {

}

In contrast to d3.scaleLinear(), d3.scaleTime() results in an empty time scale.

**Comment by jamesward** [comment]
This seems like a bug with the upstream project since WebJars just packages up d3js.  But if you do discover this is a problem with how we package or provide requirejs config, feel free to reopen.
