### ISSUE TITLE
Please Release Version: 6.7.0 and 7.6.1

### ISSUE THREAD

**Issue by cyrus07424** [webjars/d3js#34]
Please Release Version: 6.7.0 and 7.6.1

**Comment by jamesward** [comment]
For `7.x` it looks like they no longer publish the `d3.zip` with the release artifacts. Do you know where that is now?

**Comment by jamesward** [comment]
Looks like you may have to use NPM WebJars for this.  Will that work?

**Comment by cyrus07424** [comment]
I see. I will attempt use NPM version.
Thank you.
