### ISSUE TITLE
We need a webjar of d3.js 7.9.0

### ISSUE THREAD

**Issue by xiaowang03** [webjars/d3js#37]
We need a webjar of d3.js 7.9.0

**Comment by jamesward** [comment]
Can you use the NPM WebJar for this? Unfortunately I can no longer find a zip-based release.
```
org.webjars.npm:d3:7.9.0
```

**Comment by xiaowang03** [comment]
OK. We can use org.webjars.npm:d3:7.9.0.
Thank you.
